[workspace]
members = [
  "./",
  "examples/counter_timer_gauge/",
  "examples/multi_outs/",
  "examples/aggregate_print/",
  "examples/async_print/",
  "examples/raw_log/",
]

[package]
name = "dipstick"
version = "0.4.2-alpha.0"
authors = ["Francis Lalonde <fralalonde@gmail.com>"]

description = """A fast and modular metrics library decoupling app instrumentation from reporting backend.
 Similar to popular logging frameworks, but with counters and timers.
 Can be configured for combined outputs (log + statsd), random sampling, local aggregation of metrics, recurrent background publication, etc."""

documentation = "https://docs.rs/dipstick"
homepage = "https://github.com/fralalonde/dipstick"
repository = "https://github.com/fralalonde/dipstick"
readme = "README.md"
keywords = ["metrics", "statsd", "timer", "counter", "monitoring"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "fralalonde/dipstick", branch = "master" }

[dependencies]
cached = "0.4.1"
log = "0.3.8"
time = "0.1"
num = "0.1.40"
error-chain = "0.10.0"

[features]
bench = []