[workspace]
members = [
  "./",
  "examples/counter_timer_gauge/",
  "examples/multi_outs/",
  "examples/aggregate_print/",
  "examples/async_print/",
  "examples/custom_publish/",
  "examples/raw_log/",
  "examples/static_metrics/",
]

[package]
name = "dipstick"
version = "0.4.8-alpha.0"
authors = ["Francis Lalonde <fralalonde@gmail.com>"]

description = """A fast and modular metrics library decoupling app instrumentation from reporting backend.
 Similar to popular logging frameworks, but with counters and timers.
 Can be configured for combined outputs (log + statsd), random sampling, local aggregation of metrics, recurrent background publication, etc."""

documentation = "https://docs.rs/dipstick"
homepage = "https://github.com/fralalonde/dipstick"
repository = "https://github.com/fralalonde/dipstick"
readme = "README.md"
keywords = ["metrics", "statsd", "timer", "counter", "monitoring"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "fralalonde/dipstick", branch = "master" }

[dependencies]
cached = { version = "0.4", optional = true }
log = { version = "0.3", optional = true }
time = "0.1"
error-chain = "0.10"
lazy_static = "0.2.9"
derivative = "1.0"

[dependencies.num]
default-features = false
version = "0.1"

[features]
bench = []
statsd = []
default = [ "statsd" , "cached", "log" ]
